import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AuthService } from '../services/auth';
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef } from '@angular/core';

@Component({
  selector: 'app-download',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './download.html',
  styleUrls: ['./download.css'],
})
export class Download implements OnInit {

  // Define reportData with typing
  reportData: {
    liquiloan_id: number;
    clientId: number;
    activationStatus: string;
    timest: string;
    mobile: string;
    email: string;
    stateID: number;
    cityID: number;
    pincode: string;
  } | null = null;

  constructor(private http: HttpClient, private authService: AuthService, private cdr: ChangeDetectorRef) { }

  ngOnInit() {
    const clientId = this.authService.getUserId();
    if (!clientId) return;

    const apiUrl = `http://localhost:5048/api/LiquiloanReport/data/${clientId}`;
    this.http.get<any[]>(apiUrl).subscribe({
      next: (data) => {
        this.reportData = data?.[0] ?? null;
        this.cdr.detectChanges();
      },
      error: (err) => {
        console.error("Error fetching report data:", err);
        this.reportData = null;
      }
    });
  }

  downloadPDF() {
    if (!this.reportData || this.reportData.activationStatus !== 'Activated') {
      alert("No activated data available to download.");
      return;
    }

    const doc = new jsPDF();

    // Header
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 255);
    doc.text("Liquiloan Client Report", 105, 15, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Client ID: ${this.reportData.clientId}    Date: ${new Date().toLocaleString()}`, 105, 25, { align: "center" });

    // Table
    const tableData = [[
      this.reportData.clientId,
      this.reportData.mobile,
      this.reportData.email,
      new Date(this.reportData.timest).toLocaleString(),
      this.reportData.pincode,
      this.reportData.activationStatus
    ]];

    autoTable(doc, {
      startY: 35,
      head: [['ClientId', 'Mobile', 'Email', 'Activation Time', 'Pincode', 'Activation Status']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [200, 200, 200] },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(10);
    doc.text("Generated by Liquiloan System", 105, pageHeight - 10, { align: "center" });

    doc.save(`LiquiloanReport_Client${this.reportData.clientId}.pdf`);
  }
}
